### ISSUE TITLE
aarch64 Support?

### ISSUE THREAD

**Issue by wataruian** [YR-ZR0/asdf-earthly#2]
I cannot install earthly via asdf due to `uname -m` result which only supports arm64.

Is there a plan to implement it?

Will there be any complications when installing the arm64 binary to support aarch64 (are they the same?)

**Comment by YR-ZR0** [comment]
Shouldn't be a big issue, should be as simple as checking the arch in the install script

**Comment by YR-ZR0** [comment]
Hi @wataruian, if that works I'd be more than happy to accept a PR 🙂
