### ISSUE TITLE
Make this official plugin at https://github.com/asdf-vm/asdf-plugins (Question)

### ISSUE THREAD

**Issue by wataruian** [YR-ZR0/asdf-earthly#3]
Hi @YR-ZR0

I can't find any asdf plugin besides your repo; none is listed officially for earthly at https://github.com/asdf-vm/asdf-plugins too.

Is it possible to submit your asdf plugin at https://github.com/asdf-vm/asdf-plugins and make it official? 

I'm not sure what are the criteria for being "official" and being included in the list. But I think it would be great if your plugin is on the list so that others who are searching for the earthly plugin can simply take a look at https://github.com/asdf-vm/asdf-plugins repo.

I hope this makes sense.

Thanks!

**Comment by YR-ZR0** [comment]
Hey @wataruian, absolutley, i looked into that this evening and currently just dealing with a ci failure as it doesn't seem to be picking up the license file but after the test passes i've forked the plugin repo and made a folder for the earthly command. Just have the change to the table.

**Comment by YR-ZR0** [comment]
it's in as PR https://github.com/asdf-vm/asdf-plugins/pull/934

**Comment by YR-ZR0** [comment]
Hey @wataruian that PR above has been merged so it's now live 🎉
